.TH LAUNCHBEAR-WIZARD 1 "March 2018" launchbear-wizard "User Commands"
.SH NAME
launchbear-wizard - install launchbear backends for a user
.SH SYNOPSIS
.B launchbear
.RI [backend-dir]
.SH DESCRIPTION
Run this when you want to set up the backends in your home directory.
They are symlinked from the source backend dir.
Files ending ".attic" are ignored.
.SH OPTIONS AND ARGUMENTS
.TP
.B backend-dir
Where the backends are installed.
It defaults to a distribution-specific location.
.SH AUTHOR
Written and maintained by P. S. Clarke
