.TH LAUNCHBEAR 1 "2018-2025" launchbear "User Commands"
.SH NAME
launchbear - extensible program launcher
.SH SYNOPSIS
.B launchbear
[options...]
.SH DESCRIPTION
This command launches programs.
.SH OPTIONS
.TP
.BR \-d ", " \-\-backend-dir
Alternative location for backend scripts
.TP
.BR \-v ", " \-\-verbose
Emit debugging output
.SH AUTHOR
Written and maintained by P. S. Clarke
