#!/bin/bash

for fullpath in  /usr/lib/x86_64-linux-gnu/aisleriot/guile/*/*.go; do
    filename=${fullpath##*/}
    game=${filename%.go}

    echo
    echo "# Found $fullpath"
    echo "addchoice --id='aisleriot-$game' --title='Play the $game solitaire card game' --cmd='sol -v $game'"

done
