#!/bin/bash

bookmarks="$HOME/.gtk-bookmarks"
if [[ ! -e "$bookmarks" ]]; then
    echo "Missing $bookmarks - Cannot continue" 1>&2
    exit 1
fi

cat "$bookmarks" | while read location name
do
    [ -z "$name" ] && name="$(basename $location)"
    echo -n "addchoice"
    echo -n " --id='bookmark-$name'"
    echo -n " --title='Open $name'"
    echo -n " --cmd='xdg-open $location'"
    echo
done

