#!/usr/bin/python3

import sys
import os

conn_dir = "%s/.remmina" % os.environ['HOME']
if not os.path.isdir(conn_dir):
    print("# ERROR: %s does not exist" % conn_dir)
    sys.exit(1)

for conn_filename in os.listdir(conn_dir):
    if not conn_filename.endswith(".remmina"):
        continue
    # It looks like ConfigParser should work, but it doesn't!
    settings = {}
    conn_filepath = os.path.join(conn_dir, conn_filename)
    for line in open(conn_filepath):
        key, equals, value = line.partition("=")
        if equals != "=":
            continue
        settings[key] = value.strip()
    title = "Connect to %s at %s with %s" % \
               tuple(settings[k] for k in ('name', 'server', 'protocol'))
    print("""addchoice --id="remmina-%s" --title="%s" --cmd='remmina -c %s'""" %
            (conn_filename, title, conn_filepath))
