#!/usr/bin/env python


import os


def scan(location):
    print "# Files in %s" % location
    filenames = os.listdir(location)
    for filename in filenames:
        if not filename.endswith(".desktop"):
            continue
        filepath = os.path.join(location, filename)
        fileobj = open(filepath)
        properties = {}
        for line in fileobj.readlines():
            key, equals, value = line.strip().partition("=")
            if equals != "=":
                continue
            properties[key] = value
        fileobj.close()
        print " ".join((
            "addchoice",
            "--id='%s'" % filename,
            "--title='%s'" % properties['Name'],
            "--cmd='%s'" % properties['Exec'],
        ))


def main():
    locations = [
        "/var/lib/menu-xdg/applications/menu-xdg",
        "/usr/share/applications/",
    ]
    for location in locations:
        if os.path.isdir(location):
            scan(location)


if __name__ == '__main__':
    main()


